name: train-my-model

on: [push]

jobs:
  deploy-runner:
    runs-on: self-hosted
    steps:
      - name: OFC
        run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/checkout@v2
      
      - uses: iterative/setup-cml@v1

      - name: deploy
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml runner \
          --repo="$REPOSITORY_URL" \
          --labels="local,runner" \
          --idle-timeout=180 
          
          
  run:
    needs: deploy-runner
    runs-on: self-hosted
    container: 
      image: docker://iterativeai/cml
      options: --gpus all

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'

    - name: cml
      env:
        repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        apt-get update -y
        apt install imagemagick -y
        pip install -r requirements.txt
        git config --global --add safe.directory /__w/cml_cloud_case_neural_stt_local_cicd_test/cml_cloud_case_neural_stt_local_cicd_test
        # DVC stuff
        git fetch --prune
        dvc repro
        
        echo "# Style transfer" >> report.md
        git show origin/master:final_owl.png > master_owl.png
        convert +append final_owl.png master_owl.png out.png
        convert out.png -resize 75%  out_shrink.png
        echo "### Workspace vs. Main" >> report.md
        cml-publish out_shrink.png --md --title 'compare' >> report.md
        
        echo "## Training metrics" >> report.md
        dvc params diff master --show-md >> report.md
        
        echo >> report.md
        echo "## GPU info" >> report.md
        cat gpu_info.txt >> report.md
        
        cml-send-comment report.md 
